# This file was generated by GoReleaser. DO NOT EDIT.
cask "ikea-dirigera-cli" do
  name "ikea-dirigera-cli"
  desc "A CLI for the IKEA DIRIGERA Smart-Home-Hub"
  homepage "https://github.com/salex-org/ikea-dirigera-client"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ikea"

  on_macos do
    on_intel do
      url "https://github.com/salex-org/ikea-dirigera-client/releases/download/v#{version}/ikea-dirigera-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "03874e19836f2bda34cc7e0826d77f217e8e207dd8f8a58c34a910c7b73375e8"
    end
    on_arm do
      url "https://github.com/salex-org/ikea-dirigera-client/releases/download/v#{version}/ikea-dirigera-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "389e3df49038b5728c8b0d831114e3dd13d18ae59b7b667d30d1bbd4f2d2ef82"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/salex-org/ikea-dirigera-client/releases/download/v#{version}/ikea-dirigera-cli_#{version}_linux_amd64.tar.gz"
      sha256 "0a1eb8d05b7043d4e7d8efaa54bb025a19e0a9a3f32d12dcafe178fbdb9010a3"
    end
    on_arm do
      url "https://github.com/salex-org/ikea-dirigera-client/releases/download/v#{version}/ikea-dirigera-cli_#{version}_linux_arm64.tar.gz"
      sha256 "47abb46b4bf0b1687292def812c3f19675ceb10f91adf8d2b9553a6660c8851f"
    end
  end

  # No zap stanza required
end
