# This file was generated by GoReleaser. DO NOT EDIT.
cask "ikea-dirigera-cli" do
  name "ikea-dirigera-cli"
  desc "A CLI for the IKEA DIRIGERA Smart-Home-Hub"
  homepage "https://github.com/salex-org/ikea-dirigera-client"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ikea"

  on_macos do
    on_intel do
      url "https://github.com/salex-org/ikea-dirigera-client/releases/download/v#{version}/ikea-dirigera-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "18390b3a84f6e89f7eb362f055de6c3bef12f4f63679d08363b49d7360598613"
    end
    on_arm do
      url "https://github.com/salex-org/ikea-dirigera-client/releases/download/v#{version}/ikea-dirigera-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "74c02d8aa3e426a33147c6a15d1da22860eae4b3e68d7b1c2c0e4e36ce2112df"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/salex-org/ikea-dirigera-client/releases/download/v#{version}/ikea-dirigera-cli_#{version}_linux_amd64.tar.gz"
      sha256 "8530a187996c3321b7453c968dc666604a15af561d56cf32365d97337ae4dfd9"
    end
    on_arm do
      url "https://github.com/salex-org/ikea-dirigera-client/releases/download/v#{version}/ikea-dirigera-cli_#{version}_linux_arm64.tar.gz"
      sha256 "b58cf1a31e168b16a66136d25be4827565fefb0f9fb003773fafdeb035550be7"
    end
  end

  # No zap stanza required
end
