# This file was generated by GoReleaser. DO NOT EDIT.
cask "ikea-dirigera-cli" do
  name "ikea-dirigera-cli"
  desc "A CLI for the IKEA DIRIGERA Smart-Home-Hub"
  homepage "https://github.com/salex-org/ikea-dirigera-client"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ikea"

  on_macos do
    on_intel do
      url "https://github.com/salex-org/ikea-dirigera-client/releases/download/v#{version}/ikea-dirigera-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "fa63a817b32f50400c55bf2db1545828b9deb9cccb6e26bf6368ffb407b42933"
    end
    on_arm do
      url "https://github.com/salex-org/ikea-dirigera-client/releases/download/v#{version}/ikea-dirigera-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "a5afc3d88f4a310eb32eafedab9e774904c6104064260a605b6082202fa7360f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/salex-org/ikea-dirigera-client/releases/download/v#{version}/ikea-dirigera-cli_#{version}_linux_amd64.tar.gz"
      sha256 "c5684f6a07c3bf0712a42f6cc59b03ca02ca01d0d7af898535c27e3aeea87690"
    end
    on_arm do
      url "https://github.com/salex-org/ikea-dirigera-client/releases/download/v#{version}/ikea-dirigera-cli_#{version}_linux_arm64.tar.gz"
      sha256 "7303705050b674a231452e251588e6ab2b12e324645bdbc27d015db6a6e50f22"
    end
  end

  # No zap stanza required
end
